version: '3.8'
services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: pricecomparator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata:
